name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build
      env:
        CGO_ENABLED: 0
      
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: root
        password: ${{ secrets.SSH_PWD }}
        port: 22
        source: "auth"
        target: "/root"
      
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: root
        password: ${{ secrets.SSH_PWD }}
        port: 22
        source: "Dockerfile"
        target: "/root"
        
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: root
        password: ${{ secrets.SSH_PWD }}
        port: 22
        script: |
          mkdir -p /home/go/auth
          cd /home/go/auth
          rm -rf auth
          rm -rf Dockfile
          mv /root/auth ./
          mv /root/Dockerfile ./
          docker stop keauth
          docker rm keauth
          docker rmi keauth
          docker build -t keauth .
          docker run -d --restart unless-stopped -p 8080:8080 -e MYSQL_HOST=${{secrets.MYSQL_HOST}} -e MYSQL_PORT=3306 -e MYSQL_USER=${{secrets.MYSQL_USER}} -e MYSQL_PWD='${{secrets.MYSQL_PWD}}' -e MYSQL_AUTH_DB=auth --name=keauth keauth ./auth
